worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream management_api {
        server management-api:8080;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://management_api;
        }
    }
}

stream {
    # Load balancing for TCP Relay Proxy connections
    upstream relay_backend {
        server relay-proxy-1:9090;
        server relay-proxy-2:9090;
    }

    server {
        listen 8080; # Relay Port exposed to Viewer/Agent
        proxy_pass relay_backend;
    }
}
